spring:
  application:
    name: unit-test

  jpa:
    # 전송쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후 data.sql 을 실행한다.
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

# 모니터링. "prometheus" 노출을 허용
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
